version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cms
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  backend-api:
    build: ./backend-api
    environment:
      DB_DSN: root:password@tcp(mysql:3306)/cms?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - mysql
    ports:
      - "8080:8080"
  frontend-user:
    build: ./frontend-user
    environment:
      NEXT_PUBLIC_API_URL: http://backend-api:8080
    depends_on:
      - backend-api
    ports:
      - "3000:3000"
  frontend-admin:
    build: ./frontend-admin
    environment:
      NEXT_PUBLIC_API_URL: http://backend-api:8080
    depends_on:
      - backend-api
    ports:
      - "3001:3000"
volumes:
  mysql-data:
